### PR TITLE
Regenerate proto classes

### PR DESCRIPTION
**Pull request by vam-google**
- Firestore and spanner affected
- Update composer.json dependencies

### CODE REVIEW

**Comment by vam-google** [comment]
@dwsupplee, @jdpedrie Please take a look

**Comment by dwsupplee** [comment]
This is exactly what we needed :) Thank you! 👍

**Comment by jdpedrie** [comment]
looks good. I'm just running the firestore tests locally to be sure there are no regressions! will update in a couple of minutes.

**Comment by jdpedrie** [comment]
everything passed. looks good to me!

**Pull request merged**
